GET http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia2FtYWwiLCJpYXQiOjE2MzkyMDIzMTIsImV4cCI6MTYzOTIwMjMyN30.cR_pCiJhj2kV3P4M1aNVRTkX13-W_dYgh2XpON-mDlk
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia2FtYWwiLCJpYXQiOjE2MzkyMDIyODl9.YvQYVbWeC-CJZ9dTRdH_JTNrxeU_fAi8XV5abABKyXA"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia2FtYWwiLCJpYXQiOjE2MzkyMDIyODl9.YvQYVbWeC-CJZ9dTRdH_JTNrxeU_fAi8XV5abABKyXA"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{
  "username":"kamal"
}